# Generated by Django 6.0 on 2026-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_temporarymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avatar1.png', 'Cat'), ('avatar2.png', 'Dog'), ('avatar3.png', 'Robot'), ('avatar4.png', 'Ghost'), ('avatar5.png', 'Alien')], default='avatar1.png', max_length=50),
        ),
    ]
