# Generated by Django 6.0 on 2026-01-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avt1.jpg', 'Cat'), ('avt2.jpg', 'Dog'), ('avt3.jpg', 'Robot'), ('avt4.jpg', 'Ghost'), ('avt5.fpg', 'Alien')], default='avt1.jpg', max_length=50),
        ),
    ]
