# Generated by Django 6.0 on 2026-01-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_is_closed_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_closed',
        ),
    ]
