# Generated by Django 6.0 on 2026-01-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_room_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
