# Generated by Django 6.0 on 2026-01-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('avt1.jpg', 'Cat'), ('avt2.jpg', 'Dog'), ('avt3.jpg', 'Robot'), ('avt4.jpg', 'Ghost'), ('avt5.jpg', 'Alien')], default='avt1.jpg', max_length=50),
        ),
    ]
