# Generated by Django 6.0 on 2026-01-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_room_auto_delete_after_room_region_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='auto_delete_after',
        ),
        migrations.RemoveField(
            model_name='room',
            name='region',
        ),
    ]
