# Generated by Django 6.0 on 2026-01-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_profile_created_at_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
