# Generated by Django 6.0 on 2026-01-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_short_code'),
        ('chat', '0013_room_short_code'),
    ]

    operations = [
    ]
