# Generated by Django 6.0 on 2026-01-02 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_roomaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoomAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='roomaccess',
            options={'ordering': ['-accessed_at']},
        ),
        migrations.RemoveIndex(
            model_name='roomaccess',
            name='chat_roomac_room_id_38bd94_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomaccess',
            name='chat_roomac_expires_3fd9b5_idx',
        ),
        migrations.RenameField(
            model_name='roomaccess',
            old_name='granted_at',
            new_name='accessed_at',
        ),
        migrations.AddField(
            model_name='roomaccess',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomaccess',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomaccess',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomaccess',
            name='username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AlterField(
            model_name='roomaccess',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomaccess',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='chat.room'),
        ),
        migrations.AlterField(
            model_name='roomaccess',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roomaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='roomaccess',
            index=models.Index(fields=['session_key', 'room'], name='chat_roomac_session_c3e301_idx'),
        ),
        migrations.AddIndex(
            model_name='roomaccess',
            index=models.Index(fields=['accessed_at'], name='chat_roomac_accesse_69e5f6_idx'),
        ),
        migrations.AddField(
            model_name='userroomaccess',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='chat.room'),
        ),
        migrations.AddField(
            model_name='userroomaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userroomaccess',
            index=models.Index(fields=['user', 'room'], name='chat_userro_user_id_cd6ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='userroomaccess',
            index=models.Index(fields=['expires_at'], name='chat_userro_expires_d01fbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroomaccess',
            unique_together={('user', 'room')},
        ),
    ]
