# Generated by Django 6.0 on 2026-01-02 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_userroomaccess_alter_roomaccess_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarymedia',
            name='viewed',
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='chat.temporarymedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['media', 'user'], name='chat_mediav_media_i_873acf_idx'), models.Index(fields=['media', 'session_key'], name='chat_mediav_media_i_755aa2_idx')],
                'unique_together': {('media', 'session_key'), ('media', 'user')},
            },
        ),
    ]
