# Generated by Django 6.0 on 2026-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_viewed_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('global', 'Global Chat'), ('regional', 'Regional Chat'), ('private', 'Private Room'), ('local', 'LAN/WiFi Local'), ('direct', 'Direct Message')], default='private', max_length=20),
        ),
    ]
