# Generated by Django 6.0 on 2026-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
