# Generated by Django 6.0 on 2026-01-03 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_room_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='room',
            name='dm_participants',
            field=models.ManyToManyField(blank=True, related_name='dm_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
