# Generated by Django 6.0 on 2026-01-04 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_userroomjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField(db_index=True)),
                ('message_id', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('original_message', models.TextField()),
                ('edited_message', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_media', models.BooleanField(default=False)),
                ('media_id', models.UUIDField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_id', 'message_id'], name='chat_chatme_room_id_1e020d_idx'), models.Index(fields=['room_id', 'username'], name='chat_chatme_room_id_d8ab9a_idx'), models.Index(fields=['is_media', 'room_id'], name='chat_chatme_is_medi_01a959_idx')],
            },
        ),
    ]
