# Generated by Django 6.0 on 2026-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_chatmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_is_medi_01a959_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_media',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='media_id',
        ),
    ]
