# Generated by Django 6.0 on 2026-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_remove_chatmessage_chat_chatme_is_medi_01a959_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_media'], name='chat_chatme_is_medi_24a827_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['media_id'], name='chat_chatme_media_i_57f1e6_idx'),
        ),
    ]
