# Generated by Django 5.2.9 on 2026-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_chatmessage_filename_chatmessage_is_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarymedia',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporarymedia',
            name='media_type',
            field=models.CharField(choices=[('once', 'View Once'), ('normal', 'Normal Media')], default='once', max_length=10),
        ),
    ]
