# Generated by Django 6.0 on 2026-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_temporarymedia_is_expired_temporarymedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_type',
            field=models.CharField(choices=[('once', 'View Once'), ('normal', 'Normal Media')], default='once', max_length=10),
        ),
    ]
