# Generated by Django 6.0 on 2026-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_room_is_encrypted_roomencryptionkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_encrypted'], name='chat_chatme_is_encr_c312bd_idx'),
        ),
    ]
